# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `.devcontainer` directory
    directory: "/.devcontainer/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
